baseurl: /untitled


collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "home"
      permalink: "/:title/"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      permalink: "/:categories/:title/"
    